version: '3.8'

networks:
  mongo_net:
    driver: bridge

volumes:
  mongo_vol:

services:
  rotten-potatoes:
    image: henriquebrandao/desafio-rotten:v1
    restart: always
    ports:
     - 5000:5000
    networks:
     - mongo_net
    environment:
      MONGODB_DB: "admin"
      MONGODB_HOST: "mongo"
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: "mongouser"
      MONGODB_PASSWORD: "mongopwd"

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - mongo_net
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
   #   ME_CONFIG_BASICAUTH_USERNAME: mongouser
    #  ME_CONFIG_BASICAUTH_PASSWORD: mongopwd
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongo://mongouser:mongopwd@mongo:27017/

  mongo:
    image: mongo:latest
    ports:
      -  27017:27017
    networks:
      - mongo_net
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      MONGO_INITDB_ROOT_USERNAME: mongouser


